/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-aff3ct_codes
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_AFF3CT_CODES_API_H
#define INCLUDED_AFF3CT_CODES_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_aff3ct_codes_EXPORTS
#define AFF3CT_CODES_API __GR_ATTR_EXPORT
#else
#define AFF3CT_CODES_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_AFF3CT_CODES_API_H */
