/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(CCSDS_Pseudo_Randomizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(825890f846649dafab18d8060beb8e8c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aff3ct_codes/CCSDS_Pseudo_Randomizer.h>
// pydoc.h is automatically generated in the build directory
#include <CCSDS_Pseudo_Randomizer_pydoc.h>

void bind_CCSDS_Pseudo_Randomizer(py::module& m)
{

    using CCSDS_Pseudo_Randomizer    = gr::aff3ct_codes::CCSDS_Pseudo_Randomizer;


    py::class_<CCSDS_Pseudo_Randomizer, gr::block, gr::basic_block,
        std::shared_ptr<CCSDS_Pseudo_Randomizer>>(m, "CCSDS_Pseudo_Randomizer", D(CCSDS_Pseudo_Randomizer))

        .def(py::init(&CCSDS_Pseudo_Randomizer::make),
           D(CCSDS_Pseudo_Randomizer,make)
        )
        



        ;




}








